# slide 5
# phướng thức a.reshape(m,n)
import numpy as np
vector_a = np.array([5,7,2,9,10,15,2,9,2,17,28,16],dtype=np.int16)
print(vector_a)
print('-------------------------')
matrix_a = vector_a.reshape((3,4))
print('Reshape veef matrix: 3 x 4')
print(matrix_a)
print('So phan ru cua matrix:',matrix_a.size)

print('-------------------------')
print('Reshape veef vector: 2 x 6')
matrix_b = matrix_a.reshape((2,6))
print(matrix_b)
print('So phan ru cua matrix:',matrix_b.size)
# 7
a1_2d = np.array([[1,2,3],[4,5,6]])
print(a1_2d)
print('-------------------------')
print('a) revel by row (deafault oder=\'c\')')
print(a1_2d.ravel())
print('\nb) revel by column (order=\'f\')')
print(a1_2d.ravel(order='f'))
# Ví dụ các trang:9,
x = np.arange(0,12)
print(x)
x1 , x2 = np.split(x,2)
print(x1 , x2)
# 
x = np.arange(1 ,12)
print(x)
x1 , x2 , x3 = np.split(x, [2,6])
print(x1 , x2 , x3)
#   11
A2 = np.flip(A,0)
A2 = np.flipud(A)
print('lat ma tran theo hangf\: ',A2)
A1 = np.flip(A,1)
A1 = np.fliplr(A)
print('lat ma tran theo cotf\: ',A1)
#Ví dụ các trang:16 
x = np.arange(8)
print('x    = ', x)
print('--------------')
print('x + 5 = ', x + 5)
print('x - 5 = ', x - 5)
print('-x    = ', -x)
print('x * 2 = ', x * 2)
print('x / 2 = ', x / 2)
print('x // 2 = ', x // 2)
print('x ** 2 = ', x ** 2)
print('x % 2 = ', x % 2)
print('x ^ 3 = ', x ** 3)
#   
print('x = ', x)
print('--------------')
# Su dung cac phuong thuc cua Numpy
print('x + 5 = ', np.add(x, 5))
print('x - 5 = ', np.subtract(x, 5))
print('-x    = ', np.negative(x))
print('x * 2 = ', np.multiply(x, 2))
print('x / 2 = ', np.divide(x, 2))
print('x // 2 = ', np.floor_divide(x, 2))
print('x ** 2 = ', np.power(x, 3))
print('x % 2 = ', np.mod(x, 2))
# Ví dụ các trang:17
x = np.array([-2 , -1 , 0 , 1 , 2])
print( x)
print('--------------')
print(np.abs(x))
print(np.absolute(x))
thela = np.linspace(0, np.pi , 3)
print(thela)
print('----------------------')
print('sin(thela) = ', np.sin(thela))
print('cos(thela) = ', np.cos(thela))
print('tan(thela) = ', np.tan(thela))
# 19,
x = np.array([1 , 2 , 3])
print('x = ', x)
print('--------------')
print('e^x = ', np.exp(x))
print('2^x = ', np.exp2(x))
print('3^x = ', np.power(3, x))

# 
x = np.array([1 , 2 , 4 , 100])
print('x = ', x)
print('--------------')
print('ln(x) = ', np.log(x))
print('log2(x) = ', np.log2(x))
print('log10(x) = ', np.log10(x))
# 20,\
arr = np.array([20.8999,67.85657656,54.5463463])
print(arr)
print('--------------')
print(np.round(arr,1))
print(np.round(arr,2))
print(np.floor(arr))
print(np.ceil(arr))
# 23,
a = np.random.randint(1,20,10)
print('vector ban dau:\n',a)
print('--------------')
a_sort = np.sort(a)
b_sort =np.flip(a_sort)
b_sort = -np.sort(-a)
print('vector sap xep tang dan:\n',a_sort)
print('vector sap xep giam dan:\n',b_sort)

#slide 25
a_sort1 = np.sort(A,axis=0)
print('ma tran 1:\n',a_sort1)

a_sort2 = np.sort(A,axis=1)
print('ma tran 2:\n',a_sort2)

v_sort = np.sort(A,axis=None)
print('vetor :\n',v_sort)

a_sort3 = np.sort(A , axis=None).reshape(A.shape[0],A.shape[1])
print('ma tran 3:\n',a_sort3)
#slide 28
x = np.array([1,2,3,4,5,6,7,8,9,10])
t1 = np.where(x==1)
print(t1)
print('1. so phan tu thoa man dieu kien =1 ',t1[0].size)

t2 = np.where(x>10)
print(t2)
print('2. so phan tu thoa man dieu kien >10 ',t2[0].size)

t3 = np.where((x>=5)&(x<10))
print(t3)
print('3. so phan tu thoa man dieu kien >=5 & <10 ',t3[0].size)
#slide 29
arr = np.array([1,2,3,4,5,6,7],[8,9,10,11,12,13,14])
x = np.where('ma tran a : \n',arr)
print(x)
print(' so phan tu thoa man dieu kien > 4:',x[0].size)

